CREATE TABLE `TEMPERATURE_RASP2` (
  `TEMP_datec` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `TEMP_numero` tinyint(4) UNSIGNED NOT NULL,
  `TEMP_name` varchar(20) DEFAULT NULL,
  `TEMP_temp` decimal(5,2) DEFAULT NULL,
  `TEMP_hum` decimal(5,2) DEFAULT NULL,
  `TEMP_tension` decimal(5,2) DEFAULT NULL,
  `TEMP_T_ressentie` decimal(5,2) DEFAULT NULL,
   PRIMARY KEY (`TEMP_datec`,`TEMP_numero`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

SET GLOBAL event_scheduler = `ON`;
CREATE EVENT `recycling_RASP2` ON SCHEDULE EVERY 1 DAY ENABLE 
  DO 
  DELETE FROM `TEMPERATURE_RASP2` WHERE `TEMP_datec`< CURRENT_TIMESTAMP - INTERVAL 183 DAY;
